### ISSUE TITLE
[Question] How to use dependency injection?

### ISSUE THREAD

**Issue by nicolocodev** [dustinmoris/Giraffe#107]
I was playing with signalr core (alpha2) and just figured out that there is no GlobalHost class, so, [this SO answer](https://stackoverflow.com/a/46319153/1229323) shows the new way to do that. 

How do I get the IHubContext injected by .net core's DI on, say, my function?

alert: this compile but the client never get the message...

```fsharp
    let smallHandler =
        fun (next : HttpFunc) (ctx : HttpContext) ->
            task {                    
                    let lifeManager = new DefaultHubLifetimeManager<AgentHub>()
                    let hub = new SignalR.HubContext<AgentHub>(lifeManager)    
                    do! hub.Clients.All.InvokeAsync("saludar", "hola, mundo")                    
                    return! (redirectTo false "/") next ctx
            }
```
Thank you 🍻

**Comment by JonCanning** [comment]
Can use use `ctx.GetService<IHubContext<AgentHub>>()` ?

**Comment by gerardtoconnor** [comment]
Jon is right, just make sure its set up in application services just like in c# version.

on an unrelated topic  ... 
```fsharp
         hub.Clients.All.InvokeAsync("saludar", "hola, mundo")
         |> Async.AwaitTask
         |> Async.RunSynchronously
```
`InvokeAsync` is an async task so all that can be removed ... and is encouraged as your locking up thread with this method, killing throughput.

You could also probably take the `redirectTo` out of the function and pipe it on the end of your pipeline so that instead you can use the standard continuation of `return! next ctx` (next being your redirectTo.

**Comment by gerardtoconnor** [comment]
your example could be rewritten as
```fsharp
let smallHandler : HttpHandler=
      fun next ctx ->
          task {
                let lifeManager = new DefaultHubLifetimeManager<AgentHub>()
                let hub = new SignalR.HubContext<AgentHub>(lifeManager)    
                do! hub.Clients.All.InvokeAsync("saludar", "hola, mundo")     // << task async await
                return! next ctx
            }
let app = smallHandler >=> redirectTo false "/"
```

**Comment by nicolocodev** [comment]
@JonCanning yup! you are right! thank you!

@gerardtoconnor yeah, I updated the sample before any answer... you caught me on my mistake 😳 

thank you again guys
