### ISSUE TITLE
Deploy to IIS

### ISSUE THREAD

**Issue by tforkmann** [dustinmoris/Giraffe#112]
Hi there,

I really like your project. Its suits my productive system.

I just jumped in and used your template and got a local application running.
Now I want to deploy that template to a Staging System with IIS and an installed AspNetCoreModul.

What are the next steps to get the Giraffe system running on IIS?

Do I need to add a webconfig?

**Comment by nojaf** [comment]
Running Giraffe on IIS should not be any different that any other AspNetCore app.
I believe you will need a web.config like [this](https://docs.microsoft.com/en-us/aspnet/core/hosting/aspnet-core-module).

**Comment by tforkmann** [comment]
I added the web.config file.

Now I receive the following error page:
![image](https://user-images.githubusercontent.com/4168951/31536735-fecfc82a-afff-11e7-925a-789d16225aaf.png)

IIS is running on port 433 with SSL.
Do I have to adjust the port?

**Comment by nojaf** [comment]
Hmm, do you have a log file? Did you see https://github.com/aspnet/IISIntegration/issues/406?

**Comment by JonCanning** [comment]
Here's an example:

https://github.com/JonCanning/GiraffeIIS

**Comment by tforkmann** [comment]
@JonCanning Thanks a lot.

I got a little bit forward. I removed the first error message. Now I get

![image](https://user-images.githubusercontent.com/4168951/31545194-ac97b256-b01e-11e7-9676-6f82d49c1ddf.png)


I found a error description in: https://docs.microsoft.com/en-us/aspnet/core/publishing/iis?tabs=aspnetcore2x#troubleshooting-tips

Do I have to set the dll in the system path?
Or maybe I'm missing some patches because I'm on Windows Server 2008 R2

**Comment by AlbertoDePena** [comment]
I was getting an error like this....
Make sure dotnetcore 2.0 is installed in the target server.
Open command prompt and type dotnet --version

**Comment by tforkmann** [comment]
Same ...
![image](https://user-images.githubusercontent.com/4168951/31545768-fb27c3e6-b020-11e7-8566-dc6b0e6e6449.png)

**Comment by AlbertoDePena** [comment]
Is your ssl properly set up? Does it work if you use http://localhost/giraffe or http://<servername>/giraffe?

**Comment by AlbertoDePena** [comment]
If you havent deployed a dotnetcore app before, make sure to follow these steps:

https://stackify.com/how-to-deploy-asp-net-core-to-iis/

**Comment by nurges** [comment]
Are your file permissions correct? dotnet crashes and IIS returns the 502.3 error when it does not have the correct permissions. 

Give IIS_IUSRS user Read&Execute permissions to the app folder and Read&Write permission to .\logs

**Comment by dustinmoris** [comment]
Hi, glad so many people already jumped in to help you with the issue. My general advice with these type of errors is to remove as many potential error sources from the equation as possible. Seems like you don't really have a Giraffe specific problem, but a more general how to get an ASP.NET Core app running in IIS and therefore I'd recommend to just try this first. Create the smallest simplest hello world app in ASP.NET Core which doesn't use Giraffe/MVC or any other middleware and make sure to follow all the steps to get this one running in IIS. Once you've got that working then its usually a lot easier to add more middleware like Giraffe and re-deploy with your working recipe.

**Comment by tforkmann** [comment]
Hi,
sorry for the late reploy.

I did some more research...

I think it actually has to do with the fact that I tried to create the app as a subapp.
There is an open issue about it at:
https://github.com/aspnet/AspNetCoreModule/issues/150

I will try to install it as a new website an let you know if it works after.

**Comment by tforkmann** [comment]
Running it as a new app.

It just works...

![image](https://user-images.githubusercontent.com/4168951/31884345-0c9ac848-b7ed-11e7-9774-f1b87cda165d.png)

Closing the issue for now.

Thanks guys!
