### ISSUE TITLE
Should razorHtmlView detect when the .cshtml file changes?

### ISSUE THREAD

**Issue by ericharding** [dustinmoris/Giraffe#115]
When I change the .cshtml file and reload the browser I don't see the changes reflected until I restart the application.  Is that expected expected (not yet implemented) or is it a bug?

**Comment by nojaf** [comment]
On top of my head I'd try using dotnet watch, I remember that changes to cshtml files don't reflect in the browser without a server restart. Never figured out why though...

**Comment by ericharding** [comment]
Thanks. I wasn't sure it was a missing feature or if there was something off about my machine.

**Comment by ericharding** [comment]
Thanks. I wasn't sure it was a missing feature or if was my machine.

**Comment by dustinmoris** [comment]
Hi, as @nojaf said you need to [add the dotnet watch](https://github.com/dustinmoris/Giraffe/blob/master/samples/SampleApp/SampleApp/SampleApp.fsproj#L23-L29) and then it should work without a server restart (well the dotnet watch will do the restart for you in the background).

**Comment by ericharding** [comment]
The dotnet watch solution is working for me.  I'll close this issue.  Thanks for chiming in.
