### ISSUE TITLE
URL decoding strategy question

### ISSUE THREAD

**Issue by sgryt** [dustinmoris/Giraffe#117]
Hi, 

I am trying to figure out if I can make Giraffe do automatic URL decoding of string parameter values extracted from the URL path, after a matching route has been found. 

Example: Making a `HTTP GET /a/b%2Fc/d` match the route `/a/%s/d`, with the extracted string value being `a/b`.

Is that possible today? If not, would it be out of the question to support such a feature?
It would be great not to have to remember to decode all possible string input values by hand :)

Best,
Mikkel

**Comment by dustinmoris** [comment]
Hi, sorry I don't think I am 100% sure what you mean? Wouldn't the extracted value be `b%2Fc` according to your example?

**Comment by sgryt** [comment]
Hi, yes, the current implementation extracts `b%2Fc` (at least when hosted in Kestrel, not sure about IIS). 

I was wondering if it would be possible to support a hook somewhere in Giraffe, where one could enforce URL decoding of extracted string values, after a matching route has been found.

This would make it possible to roundtrip characters such as slashes and spaces in path segments (useful for, say, generating links server-side). 
Example (string) values that may need to be roundtripped in path segments: `AC/DC`, `Microsoft Corporation`. The first one must be URL encoded in order for the slash not to confuse the routing. The second one will have the space char encoded by browsers, and will thus end up having a different value if used verbatim server-side.

So, it may be useful to be able to have the library help out with the decoding (and encoding, should you choose to add link-generation features to Giraffe at some point).

Best,
Mikkel

**Comment by bizmonger** [comment]
I have a similar challenge.

I am sending a web request with "F#" as a parameter.
It gets encoded as "f%23". However, I'm not aware of the recommended practice for decoding the value in Giraffe.

Any suggestions?

**Comment by gerardtoconnor** [comment]
I see the issue now, parsed parameters should also be URL decoded for `%` tags.

I still do not see how url `/a/b%2Fc/d` matched to route `/a/%s/d` can give value 'a/b' ?? if `%2F` is a slash `/` then I would expect it to produce a parameter value of `b/c` as the partern match is "/a/`b%2Fc`/d".

@dustinmoris we can probably add a url decode in [FormatExpression](https://github.com/dustinmoris/Giraffe/blob/64cc3d79432557856992cf5fa54437670b30fdf9/src/Giraffe/FormatExpressions.fs#L68) after values extracted before passed into tuple ?

**Comment by gerardtoconnor** [comment]
string value URL decode included in pending PR #141

**Comment by dustinmoris** [comment]
@sgryt @bizmonger Can you confirm that the latest version has fixed the issue for you?

**Comment by gerardtoconnor** [comment]
I have tested this and works to this issue can be closed, I will include basic test in next PR commit.
```fsharp
[<Fact>]
let ``GET "/foo/b%2Fc/bar" returns "b/c"`` () =
    let ctx = Substitute.For<HttpContext>()
    let app =
        GET >=> choose [
            route   "/"       >=> text "Hello World"
            route   "/foo"    >=> text "bar"
            routef "/foo/%s/bar" text
            routef "/foo/%s/%i" (fun (name, age) -> text (sprintf "Name: %s, Age: %d" name age))
            setStatusCode 404 >=> text "Not found" ]

    ctx.Request.Method.ReturnsForAnyArgs "GET" |> ignore
    ctx.Request.Path.ReturnsForAnyArgs (PathString("/foo/b%2Fc/bar")) |> ignore
    ctx.Response.Body <- new MemoryStream()
    let expected = "b/c"

    task {
        let! result = app next ctx

        match result with
        | None     -> assertFailf "Result was expected to be %s" expected
        | Some ctx -> Assert.Equal(expected, getBody ctx)
    }
```
```PS
Total tests: 131. Passed: 131. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 2.3565 Seconds
```

**Comment by dustinmoris** [comment]
Thanks!

**Comment by bizmonger** [comment]
There appears to be an issue with the latest beta (310).
My elm client now fails to decode the response from Giraffe because Giraffe appears to convert the expected property names of the response to lowercase.

> { status = { code = 200, message = "OK" }, headers = Dict.fromList [("Access-Control-Allow-Credentials","true"),("Access-Control-Allow-Origin","http://localhost:8000"),("Content-Length","88"),("Content-Type","application/json"),("Date","Sat, 02 Dec 2017 12:01:58 GMT"),("Server","Kestrel"),("Vary","Origin")], url = "http://localhost:5000/bootstrap/wtf", body = "{\"providers\":[],\"platforms\":[\"RSS Feed\",\"YouTube\",\"WordPress\",\"StackOverflow\",\"Medium\"]}" }
> home.js (562,3)


I can resolve this issue if I update all my decoders to lowercase. But that is a sign that it will break other established apps as well.

**Comment by dustinmoris** [comment]
@bizmonger Hi, yes this was a breaking change in the previous version. It was made in order to align with the JSON standards across other frameworks and languages. Please see [the notes](https://github.com/dustinmoris/Giraffe/releases/tag/v0.1.0-beta-300) for more info. You can use an overload now to specify your own JsonSerializerSettings where you can set it back to PascalCase.

**Comment by dustinmoris** [comment]
@gerardtoconnor Thanks, just added that test to develop
