### ISSUE TITLE
Lightweight policy based authorization

### ISSUE THREAD

**Issue by draganjovanovic1** [dustinmoris/Giraffe#123]
I was analyzing ASP.NET new approach with policy based authorization. It looks nice but is somehow too verbose. However, it gave me some nice idea. 

Example:
```fsharp
let mustBeJohn =
    requiresAuthPolicy (fun user -> user.HasClaim (ClaimTypes.Name, "John")) accessDenied

let app =
    choose [
        route "/ping" >=> text "pong"
        route "/john-only" >=> mustBeJohn >=> text "Hi John."
    ]
```

The requiresAuthPolicy function is higher order function which accepts ClaimsPrincipal -> bool policy and can be used as a base function for all the existing auth functions.

Example:
```fsharp
let requiresRole (role : string) (authFailedHandler : HttpHandler) : HttpHandler =
    requiresAuthPolicy
        (fun user -> user.IsInRole role)
        authFailedHandler
```

@dustinmoris, if you are interested I have PR with sample and the docs ready.

**Comment by dustinmoris** [comment]
Hey, this sounds good. Feel free to send a PR for this :)

**Comment by dustinmoris** [comment]
Thanks for the PR, has been merged and will be released with the next version!
