### ISSUE TITLE
contentRoot in template causes issues when "dotnet run" is called from other directory

### ISSUE THREAD

**Issue by bartlamie** [dustinmoris/Giraffe#133]
First of all: I'm new to using Github, F#, VS Code and Ionide; so apologies if I'm doing this incorrectly.

When creating a project using `dotnet new giraffe` everything works fine when using `dotnet run` from the directory the project has been created in. However, when trying to set up a solution with a folder structure for the different projects there are errors when browsing to http://localhost:5000 after using the Ionide project explorer to run the project. It turns it this is due to the current working directory being different than expected. It can be easily replicated by setting up a new solution as follows:

```
$solution = "GiraffeSolution"
$giraffeAppName = "GiraffeTestApp"

dotnet new sln -n $solution -o $solution
dotnet new giraffe -n $giraffeAppName -o "$solution\$giraffeAppName"
dotnet sln "$solution\$solution.sln" add "$solution\$giraffeAppName\$giraffeAppName.fsproj"
dotnet build "$solution\$solution.sln"
dotnet run -p ".\$solution\$giraffeAppName\$giraffeAppName.fsproj" 
```

When browsing to http://localhost:5000 an error will appear indicating the path is invalid, for example:
`The directory name C:\Users\Admin\Documents\Programming\F\Views\ is invalid.`
The Views directory it attempts to view will be wrong

The problem lies in the following code in `program.fs`:

`let contentRoot = Directory.GetCurrentDirectory()`

If the line is replaced with `let contentRoot = AppDomain.CurrentDomain.BaseDirectory` everything works as expected, since it will no longer attempt to use the working directory.

I'm not sure if fixing this is in the scope for this template, but I figured it would be helpful for other new users; unless there are issues with the proposed solution in different scenarios of course.

**Comment by dustinmoris** [comment]
Hi, I think the suggested solution is to set the `RunWorkingDirectory` in the project file as [shown here](https://github.com/aspnet/websdk/issues/238). Let me know if this fixes the problem!

**Comment by dustinmoris** [comment]
Closing this issue as I believe the `RunWorkingDirectory` solution addresses this exact problem already, but feel free to reopen if you think the actual problem is something different.
