### ISSUE TITLE
Suave RequestErrors

### ISSUE THREAD

**Issue by forki** [dustinmoris/Giraffe#140]
Hey,

in my current project we were heavily using Suave:RequestErrors module. I can't find a replacement here so I started to port things. Are you interested in a PR whichg would add it as Giraffe functions?

**Comment by gerardtoconnor** [comment]
This sounds nice, and I'd be all for it, saves user having to remember the error codes

**Comment by forki** [comment]
see #142

**Comment by dustinmoris** [comment]
Merged and will go out with the next release.
