### ISSUE TITLE
Problem parsing %s/%d routes

### ISSUE THREAD

**Issue by forki** [dustinmoris/Giraffe#149]
I have this url:  http://localhost:8089/api/xxx/MyThing1/1/

    routef "/api/xxx/%s/%s/"  // works
    routef "/api/xxx/%s/%d/"  // does not match

**Comment by forki** [comment]
@gerardtoconnor suggested to move over to Giraffe.TokenRouter

they don't have this bug

**Comment by gerardtoconnor** [comment]
On this bug, as choice will match regex in order listed, as number can be interpreted as string, it will match before it proceeds to attempt match on next route. routef on strings always have to be last as we know they will match is all other parsing attempts fail.

if you are using `%d` in isolation, this might be related to the differing parse char usage of `%i` for int32, but '%d` being for int64?

**Comment by dustinmoris** [comment]
Confirmed that this works as expected.
