### ISSUE TITLE
Serving a page with `htmlFile` raises error

### ISSUE THREAD

**Issue by vasily-kirichenko** [dustinmoris/Giraffe#155]
A new app made from the template.
```fsharp
    let contentRoot = Directory.GetCurrentDirectory()
    let webRoot = Path.Combine(contentRoot, "public") <--- changed
    WebHostBuilder()
        .UseKestrel()
        .UseContentRoot(contentRoot)
        .UseIISIntegration()
        .UseWebRoot(webRoot)
        ...
let webApp =
    choose [
        GET >=> choose [
            route "/" >=> htmlFile "public/index.html" <--- it does not work without "public/"
        ]

        setStatusCode 404 >=> text "Not Found" ]
```
So when I go to the root path, I get:

`Access to the path 'C:\<proper app root here>\public\index.html' is denied.`

**Comment by nojaf** [comment]
Does `"./index.html"` work?

**Comment by gerardtoconnor** [comment]
Hi Vasily,

Obvious question but if you navigate to `\public` folder, what permissions are showing? Although setting the webroot tells server where www root will be for services, the folder may have been created without permissions to allow access. If you use `.UseStaticFiles()` you have to explicitly provide access outside of root but still depends on app having access to default new folder permissions

I cant see anywhere in asp.net docs saying that it adjusts/changes permissions on folder, only restricts access to it itself

**Comment by vasily-kirichenko** [comment]
I've solved it by granting IIS_USER full fights on the root folder. I'm not sure it's great, but it works. Thanks for help anyway! :)

**Comment by gerardtoconnor** [comment]
When you say root, I presume you mean `public` folder? It would not be advisable to have full permissions for IIS_USER on application root as you know.
