### ISSUE TITLE
How to send ONLY model json in response

### ISSUE THREAD

**Issue by cmeeren** [dustinmoris/Giraffe#156]
Currently migrating a web API to F# using Giraffe. Here's my testing setup (a bit simplified):

```f#
[<CLIMutable>]
type SignInParams = 
  {cardId: string
   password: string}

let signInHandler = 
  fun (next: HttpFunc) (ctx: HttpContext) ->
    let args = ctx.BindModel<SignInParams>()
    ctx.WriteJson args

let webApp = POST >=> route "/sign_in" >=> signInHandler
```

I have tried with `ctx.WriteJson` (as above), `json`, and `customJson`.

When calling this API with some `cardId` and `password` form values I expect to get the following back:

```json
{
  "cardId": "12345",
  "password": "qwerty"
}
```

What I actually get back is the following:

```json
{
  "result": {
    "cardId": "12345",
    "password": "qwerty"
  },
  "id": 28,
  "exception": null,
  "status": 5,
  "isCanceled": false,
  "isCompleted": true,
  "creationOptions": 0,
  "asyncState": null,
  "isFaulted": false
}
```

Why do I get all the other stuff back, and how can I return only my serialized model? Since I need to stick to the existing API signature, this is a no-go for me. It seems my only recourse would be to serialize the object manually and return it using `text`.

**Comment by AlbertoDePena** [comment]
Use the example in BindModel (async)...
https://github.com/dustinmoris/Giraffe#bindmodel

**Comment by gerardtoconnor** [comment]
> Use the example in BindModel (async)...
> https://github.com/dustinmoris/Giraffe#bindmodel

That's an old example that is not preferred and doesn't fix a bug if there is one ... @cmeeren almost has it correct but will explain

**Comment by cmeeren** [comment]
Ooh, my bad, I didn't see the bang after `let`. Many thanks for clarifying!

**Comment by gerardtoconnor** [comment]
@cmeeren  there is one slight issue with the code (async binded as sync) should be causing a runtime/compile error so if you would like to leave this open, I would prefer if we test and eliminate edge cases like this as other users may stumble into same issue (BindModel should not accept Tasks<'T> so easily without warning)
```fsharp
let signInHandler : HttpHandler = 
  fun next ctx -> task {
    let! args = ctx.BindModel<SignInParams>()
    return! ctx.WriteJson args
}
```
note the BindModel methos is async so must be wrapped in `task {}` if bound value to be used in handler before returning a Task<HttpFuncResult>

As a side note, it's cleaner and nicer to write handlers like `let handler : HttpHandler = fun next ctx -> ...`

**Comment by cmeeren** [comment]
@gerardtoconnor Reopening. Did you want me to do something or just leave the issue open so you can fix something?

Thanks for the style tip, I agree.

**Comment by gerardtoconnor** [comment]
@cmeeren just leave open and we can discuss options.

@dustinmoris from quick think there are three options, one breaking (but more correct), one is bit of a performance pain, other leaving as is.

1. Follow .net/c# conventions of appending async method names with 'Async' such that `BindModel<'T>()` => `BindModelAsync<'T>()` so that devs clearly know they are getting a task back and need to bind in task {} to get value (but this would extend to whole libraries naming and be big change)
2. Put a runtime typecheck warning in bind methods to provide log feedback if it is Task (this is a pretty expensive check to do every time method is called, just to prevent such fringe cases!?)
3. Leave as is and hope users don't trip up on this

STRP are not much use here to restrict Tasks as we want to prevent access rather then grant, so compile time Type restriction is not easy.

**Comment by dustinmoris** [comment]
Hmm... yeah even though this might be a pain, I think deep down I'd prefer to name it properly to `BindModelAsync` but I'll have a look if this convention is consistent across other F# libraries too and then I'll let you know what I think. My least favourite option is 2.

**Comment by gerardtoconnor** [comment]
Agreed, option 2 is not really an option, can't be over validating everything in runtime.

Not all F# libraries follow the strict ending in `Async` convention but still include Async in name eg:
[MailboxProcessor](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/control.mailboxprocessor%5B%27msg%5D-class-%5Bfsharp%5D)
`member this.PostAndAsyncReply : (AsyncReplyChannel<'Reply> -> 'Msg) * int option -> Async<'Reply>`

**Comment by dustinmoris** [comment]
Renamed all async methods according to the .NET convention of ending with `Async`.
