### ISSUE TITLE
Move main functions under one namespace (up for discussion)

### ISSUE THREAD

**Issue by dustinmoris** [dustinmoris/Giraffe#160]
This is more of a note to myself and question to current Giraffe users what you guys prefer.

I noticed that with growing functionality there's a lot of default modules/namespaces that need to be opened in almost every Giraffe application and I thought maybe it would make it easier by moving everything default under a simple `Giraffe` namespace.

For example instead of having to

```fsharp
open Giraffe.HttpHandlers
open Giraffe.HttpContextExtensions
open Giraffe.Middleware
open Giraffe.Tasks
```

it could be just

```fsharp
open Giraffe
```

Other things like Razor, XmlViewEngine, TokenParser, ComputationExpressions, etc. which are optional features will remain in their distinctive module/namespace as they are now.

However, saying that there's probably also an opportunity to merge things like `Giraffe.Razor.HttpHandlers` and `Giraffe.Razor.Middleware` into a single `Giraffe.Razor`.

Any thoughts folks?

**Comment by AlbertoDePena** [comment]
This would be very useful :)

**Comment by dustinmoris** [comment]
Done with commit d361974481359cb6d3904e28d9461455d0bc7a3e
