### ISSUE TITLE
How to use custom serialization library

### ISSUE THREAD

**Issue by cmeeren** [dustinmoris/Giraffe#163]
I'd like to use [FSharp.Json](https://vsapronov.github.io/FSharp.Json/) to serialize and deserialize (it seems to be more robust than Newtonsoft due to not automatically deserializing anything to null). Since I have a versioned API, I also need to be able to use Newtonsoft alongside for old versions of API endpoints. Is it possible to configure the JSON serializer/deserializer somewhere, and still be able to use `BindModel`, `json`, etc., and is it possible to configure multiple serializers/deserializers in a single application?

**Comment by gerardtoconnor** [comment]
Hi @cmeeren , can you confirm what functionality exactly you are looking for past null handling? Generalizing the binding system to accept all different types of json binders is just layering on abstraction and creating work in implementation and maintenance on fringe cases that are not worth it.

How we use BindModel in giraffe is extremely efficient with minimal allocations, as we read stream from the body, setting values along the way with no in-between strings/structures ... FSharp.Json is not efficient as it allocates tree like nested structures and does alot of runtime work etc.

Using custom JsonConverters, which we do support, can allow you to achieve the same functionality you are looking for where strings options of null will be set to None, of Some string so should not be a deal breaker.

The biggest reason we cannot use FSharp.Json in girrafe is that it relies heavily on reflection which is slow ... but more importantly does not have cross platform support so it will only work on windows for now. Json.net works on .net core fine and reliably so it is the preferred choice nearly every time and it would be better if we can bend Json.net to suit your needs.

If you are determined to use FSharp.Json, you can use it only on windows, and you can only compile app as dotnet4.5. to use you would need to write your own custom handlers/functions to (de)serialise.

Personally, I would just create a custom JsonConverter to avoid that headache.

**Comment by cmeeren** [comment]
I'm mostly interested in the null handling for now. I actually didn't think of custom JSON converters. How do I use those with Giraffe?

Also, thank you for the insights on FSharp.Json vs. Newtonsoft.Json. I see there are strong arguments in favor of sticking with the latter.

**Comment by gerardtoconnor** [comment]
You can create your own custom json handler to write with:
```fsharp
let myJsonSettings : JsonSerializerSettings = ...
let cjson v = makeJsonHandler v myJsonSettings
```
or when writing json in the handler, overload:
```fsharp
let myJsonSettings : JsonSerializerSettings = ...
let myHandler : HttpHandler = 
    fun next ctx -> task {
         return! ctx.WriteJson(value,myJsonSettings )
     }
```
to bind a model, similar once again, use the overload once again:
```fsharp
let myHandler : HttpHandler = 
    fun next ctx -> task {
         let myModel = ctx.BindModel<MyModel>(myJsonSettings )
         ....
     }
```
all can be found in docs
[https://github.com/dustinmoris/Giraffe#nested-response-writing](https://github.com/dustinmoris/Giraffe#nested-response-writing)

**Comment by cmeeren** [comment]
Great! I skimmed the docs, but wasn't aware that JSON converters were specified in JsonSerializerSettings, so I missed that. Thanks!

**Comment by gerardtoconnor** [comment]
no problem, if that all makes sense you can go ahead an close the issue, you can always open another if you run into difficulty, hope all works smoothly for you.
