### ISSUE TITLE
Create a sample app which shows usage of Identity with ASP.NET Core Lambda

### ISSUE THREAD

**Issue by dustinmoris** [dustinmoris/Giraffe#19]
A good way to evaluate and test if the current set of auth handlers are useful and sufficient would be to create a more involved sample app which uses something like [Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity) as the membership system.

**Comment by xdaDaveShaw** [comment]
It would also be beneficial for the Sample app to have a test suite that demo's how to test an app built against this library (I was just thinking about how to add tests to the current sample app).

Should this new sample app replace the existing one, or form part of a suite?

**Comment by dustinmoris** [comment]
Great idea. I would like to add an additional sample app. I think having a few smaller and bigger sample apps are useful where people can quickly look up things. Sometimes what someone wants to know is so simple that a big sample app might be too confusing, that is why I would like to add additional samples if possible.

**Comment by TheAngryByrd** [comment]
FYI I also have a sample app i'm working on using IdentityServerAuth with Fable and Giraffe.  Still not complete however. https://github.com/TheAngryByrd/FableWithIdentityServer .

**Comment by dustinmoris** [comment]
I put together a working sample app here: https://github.com/dustinmoris/Giraffe/blob/develop/samples/IdentityApp/IdentityApp/Program.fs

This is using the next changes on the develop branch already, but can be equally applied to the current released version.
