### ISSUE TITLE
Add a dotnet new template

### ISSUE THREAD

**Issue by dustinmoris** [dustinmoris/Giraffe#20]
See [here](https://blogs.msdn.microsoft.com/dotnet/2017/02/07/announcing-net-core-tools-updates-in-vs-2017-rc/#user-content-dotnet-new) for more information.

**Comment by xdaDaveShaw** [comment]
There's a wiki article [here](https://github.com/dotnet/templating/wiki/%22Runnable-Project%22-Templates) describing the template layout
