### ISSUE TITLE
Target lower .NET Standard

### ISSUE THREAD

**Issue by davidfowl** [dustinmoris/Giraffe#21]
Right now you're targeting netstandard 1.6, is there a reason for that? I'd try targeting 1.3.

**Comment by dustinmoris** [comment]
Hi David, as far as I know I had to target >= 1.6 because [FSharp.Core](https://www.nuget.org/packages/FSharp.Core/) doesn't target anything lower.

**Comment by davidfowl** [comment]
Hmmmmm, we should figure out why

**Comment by dustinmoris** [comment]
It could be a reminder from the previous [Microsoft.FSharp.Core.netcore](https://www.nuget.org/packages/Microsoft.FSharp.Core.netcore/1.0.0-rc-170122) package which was the FSharp NuGet lib for .NET Core while it was still in development. Perhaps it is as simple that they didn't bother with targeting anything lower than 1.6 whilst in development and now forgot to check if they can actually target a lower version. I will see if I find something otherwise I can open an issue and ask.

**Comment by slang25** [comment]
I've just had a go at this on the train. We can use one of the PCL profiles, which line up to 1.0 & 1.1, then ourselves target netstandard 1.3. However I've tried the following and the packages won't restore:

```xml
<TargetFramework>netstandard1.3</TargetFramework>
<PackageTargetFallback Condition=" '$(TargetFramework)' == 'netcoreapp1.3' ">$(PackageTargetFallback);portable-net45+win8;</PackageTargetFallback>
```

@davidfowl is my understanding correct? Any suggestions?

**Comment by slang25** [comment]
Also, in the [package description for FSharp.Core](https://www.nuget.org/packages/FSharp.Core/4.1.0) the bits in the brackets don't appear to be the official TFMs, or am I wrong about that?

**Comment by dustinmoris** [comment]
Reopening because #6 has added [RazorLight](https://github.com/toddams/RazorLight) which has targets NETStandard 1.6 again. I have opened an [issue](https://github.com/toddams/RazorLight/issues/36) to lower it at least to NETStandard 1.5.

**Comment by enricosada** [comment]
@dustinmoris `FSharp.Core` will not be lowered, see https://github.com/Microsoft/visualfsharp/issues/2501

**Comment by TheAngryByrd** [comment]
Well if we can't target a lower netstandard, how about targeting net451 as well like Kestrel?

**Comment by davidfowl** [comment]
Meh, might not be worth it at this point. Kestrel has also changed to target net46

**Comment by dustinmoris** [comment]
ok thanks everyone, I will close this issue then.
