### ISSUE TITLE
Create sample app for RESTful API

### ISSUE THREAD

**Issue by dustinmoris** [dustinmoris/Giraffe#28]
REST API for a simple CRUD app with EF, file uploads and token authentication with Identity

**Comment by dustinmoris** [comment]
I think the current two sample apps demo how any of these things can be done in Giraffe. Closing now unless someone actually has a need for a specific demo.

**Comment by ehouarn-perret** [comment]
@dustinmoris I think it would be good, a REST API demo would be a bit bigger in scope and would show how to properly use EF with giraffe.
