### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by dustinmoris** [dustinmoris/Giraffe#3]
See https://github.com/aspnet/benchmarks

**Comment by TheAngryByrd** [comment]
I did add AspNetCore.Lambda to https://github.com/TheAngryByrd/dotnet-web-benchmarks/ .  AspNetCore.Lambda was right behind Kestrel Plain!  


Disclaimer: These are super simple benchmarks with simple routing and plain text responses. 

```
CPU - Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
Operating System - Unix 15.6.0.0 (OSX)
Processor Count - 8
Dotnet Version - 1.0.0-preview2-1-003177
```

1. Kestrel Plain at 2,260,301  requests over 30 seconds
2. AspNetCore.Lambda on Kestrel  2,241,695  requests over 30 seconds
3. MVC on Kestrel 2,027,391 requests over 30 seconds

Nice!

**Comment by dustinmoris** [comment]
Nice, thanks for running those!

**Comment by dustinmoris** [comment]
I had a look at the repo and looks like you have a nice collection of different frameworks there. Did you document the results somewhere publicly so I can reference to it?

**Comment by TheAngryByrd** [comment]
Sure ill make a listing soon.

**Comment by TheAngryByrd** [comment]
https://github.com/TheAngryByrd/dotnet-web-benchmarks/blob/master/README.md#results

**Comment by dustinmoris** [comment]
These results look really great. I am glad that Giraffe (formerly known as ASP.NET Core Lambda :)) ranks so high. I would have been surprised if it wouldn't to be honest though, because the additional layer on top of plain kestrel is very thin and especially the app you tested (plain text on a GET request) is doing very little more than plain kestrel...

I wasn't sure how the conversion between C# Tasks and F# Async workflows will be, but from those tests looks like the impact is close to nothing which is great.

Many thanks for running those, I will edit the README in a bit to link to your project and the results.

**Comment by dustinmoris** [comment]
I have linked it [here](https://github.com/dustinmoris/Giraffe#benchmarks). Let me know if you would like to change or add something to it.
