### ISSUE TITLE
Serving arbitrary files with correct headers - like Suave Files.browseHome

### ISSUE THREAD

**Issue by mtnrbq** [dustinmoris/Giraffe#30]
Is this capability planned, or is there a function for this that I've missed?

**Comment by dustinmoris** [comment]
Hi, I didn't add such a function because [ASP.NET Core can already serve static files](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/static-files). Just like you configure `UseGiraffe(webApp)` in the `Startup` class you can configure `UseStaticFiles()`.

**Comment by mtnrbq** [comment]
Doh! - of course - thanks.
