### ISSUE TITLE
Question: How to get data on postback

### ISSUE THREAD

**Issue by nojaf** [dustinmoris/Giraffe#34]
Could you add an example of a postback with some data?
How to handle incoming json/form-data?
Is the aspnet modelbinding still in place?

**Comment by dustinmoris** [comment]
Hey, I will get back to you with an example over the weekend and include it into the current sample app! That is a good question, thanks for asking!

**Comment by nojaf** [comment]
Modelbinding appears to be to tightly coupled to Mvc, https://github.com/aspnet/Mvc/issues/6109.
Parsing the raw request to string (json) and converting the json to the model seems like an option.

Question is do we want other ways of extracting the model from the request? Would it make sense to have our own modelbinding?

**Comment by nojaf** [comment]
I'm able to get the json from the request

```fsharp
let readAllBytes (s : Stream) = 
    let ms = new MemoryStream()
    s.CopyTo(ms)
    ms.ToArray()

// ...

        POST >=> 
            choose [
                route "/contact" >=> (fun (ctx: HttpHandlerContext) -> 
                    async {
                        let model = 
                            ctx.HttpContext.Request.Body
                            |> readAllBytes
                            |> Encoding.UTF8.GetString
                            |> JsonConvert.DeserializeObject
                        
                        sprintf "Received model %s" (model.ToString())
                        |> Console.WriteLine

                        let json = JsonConvert.SerializeObject(model)
                        return! ctx |> (sprintf "Received %s" json |> text)
                    }                    
                )
            ]
```

Might be a good idea to provide some things out of the box for this.

**Comment by dustinmoris** [comment]
Agreed. It would be nice if there would be a function similar like `let model = bindModel<Person> ctx`.

I would expect that this function would also inspect the requests' `Content-Type` and at least support the deserialization of a JSON and XML object by default with a facility for users to extend if they have some custom binding requriements.

**Comment by nojaf** [comment]
Perhaps the return type of `bindModel` should be `Result<'TOk, 'TError`>.
See https://gist.github.com/nojaf/cf176f304a7843bbf15e6a3b3d9dc9f2

**Comment by dustinmoris** [comment]
Just published [`Giraffe.ModelBinding`](https://github.com/dustinmoris/Giraffe/blob/develop/src/Giraffe/ModelBinding.fs) this morning.

Have a look if the [updated documentation](https://github.com/dustinmoris/Giraffe#model-binding) makes sense and if you can think of any improvements?

I think an additional `bindQueryString` function would be useful which can bind a model from query string parameters, but I didn't have time to add this one as well now.

**Comment by nojaf** [comment]
Great work, simple and clean. This is a good starting point and I would create separate issues for missing functionality. F.ex. complex type properties with the form data or a combination of form data and querystring, etc.
