### ISSUE TITLE
Copy paste error in readme (webapp)

### ISSUE THREAD

**Issue by claruspeter** [dustinmoris/Giraffe#39]
This looks great!  

First time reading through your fantastic readme I noticed in the "clearResponse" section a reference to a non-existent _webApp_ variable in the last line of the example. The app itself is called "app", which of course clashes with the application builder parameter.  I notice that the "Doing it manually" section calls it _webApp_ - maybe it got copied from there.

**Comment by dustinmoris** [comment]
Thank you for taking the time to correct this! Much appreciated!
