### ISSUE TITLE
The logo

### ISSUE THREAD

**Issue by dustinmoris** [dustinmoris/Giraffe#43]
Hey everyone,

I set up a design contest for the Giraffe logo and I have filtered down all logos to what I believe are the 3 best options so far and I would like you to help me pick the right logo!

All 3 designers still have a bit more than a day to make any changes to the logos. If you really like a logo, but think it deserves a few more changes then please let me know and I will forward the feedback.

These are the options:

![image](https://cloud.githubusercontent.com/assets/4580714/25267963/d8bfe89c-266e-11e7-904c-6c9be9f3ceca.png)

Thanks for helping!

**Comment by slang25** [comment]
These are looking great.

I'm not a fan of A, it's not as striking as the others, and looks more suited to a fashion brand than a tech logo.

B is very nice, and closest to your original concept. It's simple while very well executed.

C is very clever, and again well executed. It has a great balance between simplicity and being recognisable as a giraffe. I'm a big fan of this one.

For me my preference is from favourite to least: C, B, A

**Comment by nojaf** [comment]
I'm in favor of B.

**Comment by MiloszKrajewski** [comment]
C >= B > A

**Comment by jimmydburr** [comment]
I would say A is the more _classic_ of the three.

**Comment by dustinmoris** [comment]
For those who like C, there is this variation which just came in:

![image](https://cloud.githubusercontent.com/assets/4580714/25275286/5089c146-268c-11e7-9723-1092ea5e81dc.png)

**Comment by slang25** [comment]
The new variants are awesome, nice font and colour. My vote is for the one on the left.

My daughter (4 yrs) says she like giraffe A, "cause it's doing the splits" (she's now running around doing the splits)

**Comment by dustinmoris** [comment]
lol kids are awesome :) Thanks for the help!

**Comment by dustinmoris** [comment]
Thanks everyone for the help. C was the winner and even though it wasn't my first choice in the beginning I think it is a fantastic logo now.
