### ISSUE TITLE
Swagger support

### ISSUE THREAD

**Issue by dkholod** [dustinmoris/Giraffe#52]
Is it possible to make use of existing swagger and JWT middleware in Giraffe. 
Just started to look at this project and will appreciate if you can speed me up.

Thank you.

**Comment by dustinmoris** [comment]
Hi, could you give me an example of swagger and JWT middleware with a normal ASP.NET Core or MVC application?

**Comment by imetallica** [comment]
@dustinmoris This is na example of JWT middleware https://dev.to/samueleresca/developing-token-authentication-using-aspnet-core

Also, might suggest you create another set of functions:
- `signIn` -> Helper for sign in
- `cookieClaims`
- `tokenClaims`

This would require you to add `Microsoft.AspNetCore.Authentication.JwtBearer` and `Microsoft.AspNetCore.Authentication.Cookies` as direct dependencies to `Giraffe`.

**Comment by kspeakman** [comment]
I was able to get default JWT middleware working for API routes.

**Install JWT package (NuGet version)**

`dotnet add <project> package Microsoft.AspNetCore.Authentication.JwtBearer`
`dotnet restore`
*if VS Code / Ionide, make any change to .fsproj to trigger detection of new package*

**Configure it**

```fsharp
(* Program.fs *)
...

let configureApp (app : IApplicationBuilder) =
    let jwtOptions =
        JwtBearerOptions(
            Audience = "<your api url>",
            Authority = "<your token service>"
        )
    app.UseJwtBearerAuthentication(jwtOptions) |> ignore
    ...
    app.UseGiraffe apiApp

// requires: open Microsoft.Extensions.DependencyInjection
let configureServices (services : IServiceCollection) =
    services.AddAuthentication() |> ignore
    ...
```

**Setup HttpHandler for requiring authentication**

*I __think__ I found AuthorizeAttribute's version of this code [here](https://github.com/aspnet/Security/blob/patch/1.1.3/src/Microsoft.AspNetCore.Authorization/Infrastructure/DenyAnonymousAuthorizationRequirement.cs). Hard to trace because it is so far removed from the Attribute.*

```fsharp
// forgive my non-fish implementation
let authenticated ( ctx : HttpContext ) =
    let isAuthenticated =
        not ( isNull ctx.User )
            && not ( isNull ctx.User.Identity )
            && ctx.User.Identities |> Seq.exists (fun x -> x.IsAuthenticated)
    let result =
        if isAuthenticated then        
            Some ctx
        else
            None
    async.Return result
```

**Use it in routes**

```fsharp
let apiApp =
    choose [
        authenticated >=>
            choose [
                route "/" >=> text "Hello world, from Giraffe!"
                setStatusCode 404 >=> text "Not Found"
            ]
        setStatusCode 401
    ]
```

I got this working with Auth0 (OIDC-conformant API turned on), but others should work.

**Comment by dustinmoris** [comment]
Awesome work! I will try to incorporate this into a small sample app which can be checked into the repo or if you like you can try it yourself and submit a PR :)

**Comment by dburriss** [comment]
Maybe this should be 2 separate issues? They are 2 very different requests. I would love to see Swagger support. The [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#swashbuckle-apiexplorer-and-routing) states "You must use attribute routing for any controllers that you want represented in your Swagger document(s)" which is a problem I imagine. It would be great if we could use the Swashbuckle middleware.

**Comment by gerardtoconnor** [comment]
@dburriss yes, these are two separate issues, the JWT one being addressed in this issue (PR pending), Swashbuckle/Swagger being addressed in #79.

In #79, assuming users are referring to "Swashbuckle like" auto-mapping api to swagger, this would be done with custom mapping functions as, like you mentioned, Swashbuckle's annotations only work on classes / methods, whereas f# & giraffe compose reusable functions (of same types) that require mapping for each route instance, not each type declaration.

As such, we can probably close this issue once JWT PR merged, and then link to #79 for the continued implementation discussion of Swagger.

**Comment by catalintoma** [comment]
Hi guys,

What about the token generation part? I haven't been able to find if this functionality is part of Asp Core or will we need to write our own method.

**Comment by kspeakman** [comment]
@catalintoma Token generation uses the same middleware as above (`UseJwtBearerAuthentication`), but you have to include more options to generate tokens.

[https://pioneercode.com/post/authentication-in-an-asp-dot-net-core-api-part-3-json-web-token]()

**Comment by catalintoma** [comment]
@kspeakman Thanks, I think I've read that article before.

Just to be clear, the middleware has options to automatically create the token generation route (something like POST /token) ?

**Comment by kspeakman** [comment]
@catalintoma Looks like the middleware is only for verification actually. The token creation happens in the 2nd and 3rd code blocks of the linked article. Sorry, I do not have an F# worked example for you -- I use external auth token providers, so I only deal with token verification.

**Comment by Sebosek** [comment]
@catalintoma, @kspeakman is right, it's "just" verification middleware. Here is another example for .netcore 2.0.

```
let jwt = requiresAuthentication (challenge JwtBearerDefaults.AuthenticationScheme)

let webApp =
    choose [
        GET >=>
            choose [
                route "/" >=> razorHtmlView "Index" { Text = "Hello world, from Giraffe!" }
                route "/protected" >=> jwt >=> text "Authorized"
            ]
        setStatusCode 404 >=> text "Not Found" ]

let configureServices (services : IServiceCollection) =
    let sp  = services.BuildServiceProvider()
    let env = sp.GetService<IHostingEnvironment>()
    let viewsFolderPath = Path.Combine(env.ContentRootPath, "Views")
    services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(fun x ->
        let events = JwtBearerEvents()
        events.OnAuthenticationFailed <- fun context ->
            context.Fail "Authentication failed"
            Task.CompletedTask

        x.RequireHttpsMetadata <- false
        x.Authority <- "http://localhost:5050/identity"
        x.Audience <- "sebastian"
        x.Events <- events) |> ignore
    services.AddRazorEngine viewsFolderPath |> ignore
```

I wanted to prepare also an example for generating JWT token, but unfortunately, not all required libraries have been ported to netstandard2 yet.
But at least you can try to use [OpenIddict](https://github.com/openiddict/openiddict-core) as far I know it's one of solution which been ported to netcoreapp2.0.

**Comment by rmotyka** [comment]
I've put some JWT generator there:  [JWT generator](https://gist.github.com/rmotyka/d434e6a85dc0a005e3ce8410cda1f3c6)

**Comment by xperiandri** [comment]
https://channel9.msdn.com/Series/aspnetmonsters/ASPNET-Monsters-39-Creating-Tokens-for-Basic-API-Authentication isn't it about that?

**Comment by torhovland** [comment]
I've put together a sample application for JWT auth with .NET Core 2. It also demonstrates pulling authenticated data from claims and making use of that in web operations. It's available here: https://github.com/dustinmoris/Giraffe/pull/101

**Comment by dustinmoris** [comment]
I've renamed the issue as the JWT support question has been sufficiently answered I believe. Thanks @torhovland @rmotyka @Sebosek @kspeakman for your help on this!

**Comment by dustinmoris** [comment]
Actually I am going to close this as a duplicate and suggest to continue any Swagger support conversation in #79.
