### ISSUE TITLE
Websockets, Channels, PubSub and Presence

### ISSUE THREAD

**Issue by imetallica** [dustinmoris/Giraffe#55]
Hi everyone, I'm up for grabs to a Websocket + PubSub + Presence implementation for Giraffe. I think that, with the needs of realtime web, and from my experience seeing people coming from Rails to [Elixir + Phoenix Framework](https://hexdocs.pm/phoenix/Phoenix.html) for realtime + performance, it's something we should consider to have an implementation in Giraffe out of the box.

So I want to open a discussion on the idea. My initial roadmap is to have the following:

1. Add websockets + channels to the routing layer of Giraffe.
2. Create a JS library to handle the channel layer.
3. Add support for PubSub.
4. Add presence on top of PubSub.

For someone who is not familiar with Channels, the ideia is that we can route messages to specific `topic:subtopic`, much in a way an URL route is, so you can run authentication/authorization rules specific for each channel.

For the PubSub layer, well, if you are running multiple instances of `Giraffe`, you need a way to broadcast to all connected clients to that channel, independently if they are connected to node 1 or 2. So, my idea is to have an in-memory backend for testing purposes and an Redis backend. Maybe use the `Microsoft.Extensions.Caching.*` namespace (?). Probably need some advice here. :)

For the Presence layer, the idea is to have a [CRDT](https://en.wikipedia.org/wiki/Conflict-free_replicated_data_type), so you can, for example, count the amount of devices for account X, connected in the channel, at the same time. For example, if `John` is connected both on his phone and on a web browser, it should show `John` only once. Or you can just show `John <mobile> <desktop>`, for example. The sky is the limit. :)

Thoughts?

**Comment by gerardtoconnor** [comment]
@imetallica Hey, when you say 'you're up for grabs', are you saying you're building it? 

I fully agree it would be a nice thing to work towards, but I noticed you didn't mention SignalR at all, it seems bit mad to build a whole new system from scratch when same can be achieved with a system built on top of asp.net core already?

It is possible to use the low-level api's in SignalR to avoid all the hubs controllers and proceed to replicate HttpHandler pipelines for subscribed events etc. so it becomes a task of integrating SignalR into functional pipeline more then anything else.

**Comment by imetallica** [comment]
@gerardtoconnor yes I'm up for building it. The reasoning I didn't mention SignalR is because there is no implementation yet for core. We could wait or we could roll our own and when SignalR comes we migrate to use it.

**Comment by rodrigovidal** [comment]
@imetallica https://github.com/aspnet/SignalR

**Comment by dustinmoris** [comment]
With SignalR being ported to ASP.NET Core by Microsoft is there still anything to do here or can this be closed?

**Comment by imetallica** [comment]
Yeah it's pretty pointless when SignalR is in place so can be closed.
