### ISSUE TITLE
dotnet run fails to run project

### ISSUE THREAD

**Issue by rishavs** [dustinmoris/Giraffe#66]
Hi
I created a sample project using `dotnet new giraffe`
After this i used `dotnet restore`
When i do dotnet run, i get the following error;
````
PS C:\Users\Mockingbird\DevSpace\DotNet\giraffe> dotnet run
C:\Users\Mockingbird\DevSpace\DotNet\giraffe\Program.fs(62,10): error FS0039: The field, constructor or member 'UseWebRoot' is not defined. [C:\Users\Mockingbird\DevSpace\DotNet\giraffe\DotNet.fsproj]

The build failed. Please fix the build errors and run again.
````

my dotnet version is 1.0.4
I am on windows 10, 64 bits

**Comment by slang25** [comment]
@rishavs thanks for the bug report.

This was fixed yesterday in #64 and should be resolved in the next release.

For now you can manually workaround it by simply moving the `)` at the end of the line 62 to the end of line 61.

**Comment by dustinmoris** [comment]
Hi, sorry about the delay in getting the new NuGet package out. I have just released the fix by @GraanJonlo .

Make sure you pull the latest `giraffe-template`:

```
dotnet new -i giraffe-template::0.1.6
```

That should work, I just pulled it myself and tested that a clean `dotnet restore` and `dotnet run` works as expected.

Thanks @slang25 for helping @rishavs with the workaround!

**Comment by rishavs** [comment]
Thank you for the quick fix.
