### ISSUE TITLE
Parameter-less Function is Treated as a Value when Composed

### ISSUE THREAD

**Issue by vtquan** [dustinmoris/Giraffe#67]
If I compose a parameter-less function, ``route "/" >=> noParameterFunction ()`` for example, my function is being evaluated on start and treated as a value.

To reproduce, start out with a new project from the template make the modification below

```fsharp
let noParameterFunction () =
    printfn "Hello"
    text "Hello"


let webApp = 
    choose [
        GET >=>
            choose [
                route "/" >=> noParameterFunction ()
            ]
        setStatusCode 404 >=> text "Not Found" ]
```

If you call ``dotnet run``, "Hello" will be printed to console without going to the route. Going to the route will not call the printfn statement again.

Restoring the route code back to ``route "/" >=> razorHtmlView "Index" { Text = "Hello world, from Giraffe!" }`` while keeping the function and "Hello" will not be printed after ``dotnet run``

**Comment by JonCanning** [comment]
Remember, an HttpHandler looks like this:

`HttpContext -> Async<HttpContext option>`

So `noParameterFunction()` is executed, logs "Hello" and returns an HttpHandler that prints "Hello"

Try this

```
let noParameterFunction ctx =
  async {
    printfn "Hello"
    return! text "Hello" ctx
  }
```

**Comment by gerardtoconnor** [comment]
@JonCanning is spot on

It can be very useful though for when you want to pre-compile data before returning the handler as the code body is only executed once at startup and does not need to be run each time.

If you remove currying, it is easy to see why the body only runs once as per below which is the same as yours only wrapping a ctx function:
```f#
let noParameterFunction () =
    printfn "Hello"
   /// val text : string -> HttpContext -> Async<HttpContext option>
    (fun ctx -> text "Hello" ctx)
```
although Jon's example is fine, you can just as easily avoid async wrap with
```f#
let noParameterFunction ctx =
    printfn "Hello"
    text "Hello" ctx
```
As there is no async binding other than the return, which is itself producing an async result. You only need to use async binding when your handler is itself doing some waiting, otherwise just return the async of the internal handler being used.

**Comment by vtquan** [comment]
Thank you for the explanation. I am still not clear on why the code body only runs once. Is it because non async code is only being evaluated once or the process of composing treat all parameter-less function as a value?

**Comment by gerardtoconnor** [comment]
This might help explain.
Every HttpHandler is a function, it takes in a `HttpContext` and returns `Async<HttpContext option>`, I find that a nice way to write all handlers, regardless of multiple inputs are
```f#
let noParameterFunction =
    fun (ctx : HttpContext) ->
        printfn "Hello"
        text "Hello" ctx

let myText (txt:string) =
    fun (ctx: HttpContext) ->
         printfn txt
         text txt ctx

let preCompiled () =
     // only evaluted once when funtion called
     let serverStart = DateTime.Now.ToString()
     // now return a HttpHandler Function that contains reference to our value evaluated on startup
     fun ctx -> text serverStart ctx
```
The value `webApp` that contains all the routes and compositions is fully evaluated into a tree of HttpHandler functions that bind together, therefore expressions in your pipeline will evaluate till they return HttpHandlers to bind & Compose to the rest of the pipeline. It is similar to using the `>>` operator, composing two normal functions together into a pipeline, if you did `fn1 = fn2 () >> fn3`, provided the result of `fn2 ()` is a function of the same type for the input of `fn3`, we can compose together into one `fn1` function, but `fn2` is never run again after initial execution as it has returned its function result.

**Comment by vtquan** [comment]
I got it now. The functions are evaluated so that they can be passed on to form the HttpHandler function. Thank you.
