### ISSUE TITLE
HttpHandler is inferred to be generic when in a different file

### ISSUE THREAD

**Issue by ian-moore** [dustinmoris/Giraffe#68]
Starting from the dotnet Giraffe template, if I try to define any HttpHandler outside of the Program.fs file, the compiler complains that my HttpHandler functions are generic. Which is weird because code lens shows the correct signature.

![image](https://user-images.githubusercontent.com/1709416/27981701-f0d85a4e-6355-11e7-8890-8231d9e35592.png)

If I annotate every thing to be HttpHandler it compiles fine, but I'm confused why I am required to do that here.

**Comment by dustinmoris** [comment]
This is weird indeed. I don't have a good explanation for it, but I will annotate all http handlers in the Giraffe library, which should fix this issue I think. It won't hurt to explicitly annotate all existing http handlers.

**Comment by ian-moore** [comment]
I tried with the updated version and seeing the same behavior on curried HttpHandlers.... I'm playing around with it from the source and still stumped. Thankfully there are easy workarounds

**Comment by ian-moore** [comment]
I moved the auth related functions of the SampleApp into a separate file, and it seems to only be a problem with HttpHandlers that have another handler as an argument

![image](https://user-images.githubusercontent.com/1709416/28390822-3936ad32-6ca1-11e7-8b63-f96d5e40c4a8.png)

**Comment by dustinmoris** [comment]
Cool.. thanks for drilling down to the bottom of this issue!
