### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by nojaf** [dustinmoris/Giraffe#73]
No idea how hard this is but I was wondering if we could benefit from a gitter channel?

**Comment by dustinmoris** [comment]
Yeah that is a good idea. To be honest I prefer Slack, because I find it more intuitive to use and I have the client already installed on all my devices and also on my phone, so I am more likely to see and respond to any questions via Slack, but if there's a strong push for Gitter I wouldn't mind that either.

**Comment by nojaf** [comment]
I like Slack as well, no particular preference on my end. Let's wait for some more opinions.

**Comment by gerardtoconnor** [comment]
+1 slack ... it's easier to use on mobile

**Comment by EricDw** [comment]
I will join! I'm brand new to F# and .NET but I love the idea of Giraffe and would like to help.

**Comment by dustinmoris** [comment]
Quick question, do you think a new Slack Team is what you'd prefer or a new channel in the functional-programming Team where there is already an fsharp and fsharp-beginners room as well?

**Comment by nojaf** [comment]
A channel in the functional programming channel sounds like a good idea.

**Comment by EricDw** [comment]
I agree with nojaf, the latter sounds best.

**Comment by dustinmoris** [comment]
Just created the channel #giraffe

**Comment by EricDw** [comment]
How do we join? I think the invite for the Functional Programming channel is down?

**Comment by dustinmoris** [comment]
Ah sorry I will link it in the README as well. I think you need to get an invite via this app: https://fpchat-invite.herokuapp.com/

**Comment by dustinmoris** [comment]
Let me know if it works and then I'll update the README.

**Comment by EricDw** [comment]
Worked perfectly! Thank you!
