### ISSUE TITLE
Razor is not affected by the _ViewStart file 

### ISSUE THREAD

**Issue by vtquan** [dustinmoris/Giraffe#74]
Razor uses ViewStart file to know what code to run before every views. I created the _ViewStart.cshtml file in my Views folder with the following code

```cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Home Page";
}
```

Neither parts affect how my view is rendered. You can't manually set the name of the ViewStart file in ASP.NET Core so I don't think that I am missing a set up step or giving it the wrong name either. Razor did noticed my _ViewImport.cshtml file, which is also a file that razor look for to set thing up, in the same location so it shouldn't be because of putting it in the wrong location.

**Comment by nojaf** [comment]
What version are you on? I believe Giraffe used to use `RazorLight` instead of `AspNetCoreMvc`. So maybe you are using an older version of Giraffe and RazorLight doesn't use the concept of a `ViewStart` file.

Not sure though.

**Comment by vtquan** [comment]
I am using Giraffe 0.1.0-alpha025 and Giraffe.Razor 0.1.0-alpha001 which should be the latest version for both.

**Comment by nojaf** [comment]
I'm able to reproduce this, it doesn't work and there is not much to go on.
I'm guessing something is missing in the [middleware](https://github.com/dustinmoris/Giraffe/blob/master/src/Giraffe.Razor/Middleware.fs) but that is a wild guess.

**Comment by dustinmoris** [comment]
hey thanks for reporting this. I am currently working through the changes with the task changes that have been submitted via a PR and after that I'll pick this one up next!

**Comment by vtquan** [comment]
Good to know that you'll look into it. Thanks.

**Comment by EricDw** [comment]
I was able to use the 

@RenderPage("~/Views/_Header.cshtml")

Not sure if I have the wrong syntax or it is related.

I get a ""RenderPage" is out of context" error.

**Comment by EricDw** [comment]
Was not able to use*****

**Comment by EricDw** [comment]
I would like to clarify that the 

`@{
          Layout = "_Layout";
     }`

Logic does indeed work for me.

As for the 

`@RenderPage("~Views/SomeHtml.cshtml")`

code, after reading the ASP.NET Core Razor docs I think I'm just using system incorrectly.

**Comment by nojaf** [comment]
@EricDw did you place the `@{ Layout = "_Layout"; }` inside the `_ViewStart.cshtml` file or in the view itself?

**Comment by EricDw** [comment]
@nojaf `@{ Layout = "_Layout"; }` is in the view itself. I am pretty sure that ASP.NET Core no longer uses `@RenderPage` instead I am using `    
    @{
        await Html.RenderPartialAsync("_Header");
    }
`
inside the `Layout.cshtml` and it that does the job.

**Comment by nojaf** [comment]
Ok but I believe the original issue that @vtquan has is that setting the `Layout` from `_ViewStart.cshtml`  doesn't work.
If he has a hundred views then setting the `Layout` from the view isn't really an option.

**Comment by vtquan** [comment]
@nojaf Yes, that is my issue.

**Comment by lukethenuke** [comment]
This is fixed by changing the `isMainPage` parameter to `true` in the call to `IRazorViewEngine.FindView`

**Comment by dustinmoris** [comment]
Thanks for the fix. I just released it with the newest NuGet package: Giraffe.Razor 0.1.0-beta-002!
