### ISSUE TITLE
.NET Core SDK 2.0 is supported or will be?

### ISSUE THREAD

**Issue by ryukinix** [dustinmoris/Giraffe#76]
### Description
For now the README.md seems to point that Giraffe is design to build on top of the lastest released SDK, which for now is the SDK 1.0 and runtime 1.1. I tried, naively build the provided template with the SDK 2.0.0 preview 2 and doesn't works. So, for now, this is the expected, right?

But you have plans to support SDK 2.0.0 before release too? Or only after the official release?

Thanks anyway for that great web framework!

### System/SDK version
Just for completeness sake, I'll add my current version info from `dotnet --info`
```
❯ dotnet --info
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     manjaro
 OS Version:  
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /opt/dotnet/sdk/2.0.0-preview2-006497/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
 ```

**Comment by dustinmoris** [comment]
Hi, Yes I definitely plan to support .NET Core 2.0, but I haven't had time to play with preview 2 yet. From previous experience I thought it might be better to wait for the final RTM, because they often changed quite a few bits very last minute and I don't want to migrate the library multiple times, but if the support for .NET Core preview 2 is much desired I can definitely work on it and release pre-release of Giraffe on that version too.

**Comment by ryukinix** [comment]
Good to hear it, @dustinmoris! Awesome job.

I'll be watching your progress.

I'm very excited about .NET Core 2.0, seems they improved a lot and fixed annoying bugs (which I suffer on some cases, like the wrong f# templates for console apps and others things). Another thing I expect is, but I don't have sure, If they will release support for Linux x86.

**Comment by Banashek** [comment]
Looks like aspnetcore 2.0.0 was released on [nuget](https://www.nuget.org/packages/Microsoft.AspNetCore/2.0.0).

I assume the [cli tools](https://github.com/dotnet/cli/tree/release/2.0.0) will be released soon as well. 

There have definitely been some breaking changes, but I'm not sure how much of it will affect Giraffe directly.

**Comment by dustinmoris** [comment]
Thanks, weird I didn't see any official announcements of ASP.NET Core 2.0 yet, but you're right... it's been out for 3 days now! I actually also didn't think that netstandard2.0 is a new netstandard rather then a continuation of the previous one. This breaks the whole concept of netstandard, that when you target a lower version it will always work on a platform which supports a higher version. I am really confused... I don't understand why adding more APIs to netstandard2.0 stops compatibility with the old standards... anyway... given that this is the case I will indeed have to wait for all other dependencies to update first.

**Comment by Banashek** [comment]
Yeah I pulled down the repo and just started shoving 2.0 dependencies at it. The first thing I noticed was an f# compiler error, which is when I stopped. I think that will be the only thing that will need to be waited on.

Aspnet stuff -> 2.0
System stuff -> 2.0
Json -> [not yet](https://github.com/JamesNK/Newtonsoft.Json/issues/1383)

though [i'm not sure how much these matter](https://github.com/dotnet/standard/blob/master/docs/faq.md#what-about-the-breaking-change-between-net-standard-1x-and-20)

Since 2.0 is [a superset with no breaking changes](https://github.com/dotnet/standard/blob/master/docs/faq.md#if-there-is-no-breaking-change-why-call-it-net-standard-20) I _feel_ like it should be attemptable.

Every time I think I understand this stuff I look into it and something like "we don't need to do  [semver](http://semver.org/) because we _feel_ it's a big change" happens.

Anyhoo, If I have some time I'll look into the F# issue (it was an error about multiple imports of `System.Runtime` on compilation) and see if I can't sort it out.

**Comment by dustinmoris** [comment]
nice... let me know how you get on with it and if you want me to help with something, otherwise I'll just wait for the PR :D

**Comment by Banashek** [comment]
So I got the projects building with [these changes](https://github.com/Banashek/Giraffe/commit/72c3293aca917f46fbce14dd171f7075d8e17a49), but am running into all sorts of weird nuget-type errors.

I was at it for a while and got down pretty far the nuget/netcore rabbit hole.

Decided to take a step back and see if everything worked minimally.

I made [a copy project with minimal dependencies](https://github.com/Banashek/Juraff) to see if it would work. It seems to work, but this is just targeting netcore and I only tested the simple application (which uses some giraffe features).

Somewhere between these two repos is the answer lol.

Figured I'd put the information here for reference.

**Comment by ryukinix** [comment]
FYI, [.NET Core 2.0](https://blogs.msdn.microsoft.com/dotnet/2017/08/14/announcing-net-core-2-0/) was released two days ago!

**Comment by Banashek** [comment]
Yeah it's pretty exciting. I made sure to install it before starting on any of the porting work. I've got the partial working solution in the copy project repo I made. It's stripped down to only the necessary bits to get giraffe working on dotnet core, but doesn't include any of the CI or net461 parts. I'll look at it a bit more today.

**Comment by Banashek** [comment]
Got passed all the weird runtime issues. Everything is building and tests are passing. I just need to fix up the samples and I should have a PR in today.

![image](https://user-images.githubusercontent.com/7094571/29473860-3a6c8b48-840e-11e7-9d58-174075e94aa0.png)

**Comment by Banashek** [comment]
`error NU1202: Package Microsoft.AspNetCore 2.0.0 is not compatible with net46`

I've got everything tested under netstandard2.0

Not sure if everything will work with the net46 dependency

**Comment by Banashek** [comment]
Additionally, I don't think I'll be able to test 461 (which should be compatible if you want to bump it) on my mac. It could be set up in docker, but I don't think I have the time to set that up at the moment.

**Comment by Banashek** [comment]
So I've got everything working targeting netstandard2.0/netcore2.0 [here](https://github.com/Banashek/Giraffe) except for the samples.

The `SampleApp` has the following error:
![image](https://user-images.githubusercontent.com/7094571/29474971-bb7871e4-8412-11e7-9a65-1ad64b34bc21.png)

And the IdentityApp has errors to do with wherever all the identity stuff got moved to, but it shouldn't be too much work to translate it over.

I don't know if I'll be able to actually get to that stuff this weekend (just got booked for meetings, and then will be away from the computer), but I've checked in 90% of what needs to be done in my repo.

Let me know if you'd like that PR'd into a netcore2.0 branch or something where the last 10% can be finished up.

**Comment by dustinmoris** [comment]
Hi I just created a netstandard20 branch. Feel free to submit the PR and I will merge it in there and finish the last 10% :)

**Comment by NinoFloris** [comment]
Any easy way to consume it for now?

**Comment by dustinmoris** [comment]
Hi @NinoFloris I aim to work on the 2.0 branch this weekend and hopefully have a new pre-release package ready by then which you can consume. I'll keep you posted here...

**Comment by dustinmoris** [comment]
Hey, I am going through your changes and targeting 461 all works too, so might have a new release ready tonight or tomorrow. There's one things which I am surprised and I wanted to know how it works now without `FSharp.Core` and `FSharp.NET.Sdk`??

**Comment by NinoFloris** [comment]
F# compiler and targets have been rolled into the Microsoft.NET.Sdk since
2.0

**Comment by dustinmoris** [comment]
Nice, that's great, thanks!

**Comment by dustinmoris** [comment]
Just released all packages with the upgrade to netstandard2.0 and net461. Enjoy!

**Comment by JonCanning** [comment]
🎉
