### ISSUE TITLE
How to pass Option<T> instead of T to handlers

### ISSUE THREAD

**Issue by Lanayx** [dustinmoris/Giraffe#77]
I'd like to use razorView, json and other http handlers not with T, but with Option<T> type (since data comes from db, or another service and can be missing). How do I do that?

**Comment by Lanayx** [comment]
Never mind.

I decided to go with Result instead of Option for model and this snippet:

 ```
       return! match result with 
               | Ok model -> json model context
               | Error error -> (setStatusCode 500 >=> text error) context
```

**Comment by gerardtoconnor** [comment]
Hi Lanayx,

I was in the middle of writing a response when you closed but from your own response, `Result` is probably better truthy container as it includes details on fail/error and is internally a struct which is well suited to short-lived evaluation of parameters like this. 

With any handlers/functions that take concrete types for binding, you should do the filtering yourself before calling a binding (json/razor), explicitly providing path to take when model does not exist as you have done above.

**Comment by Lanayx** [comment]
Thank you for confirmation!
