### ISSUE TITLE
Breaking changes between Giraffe 0.1.0-alpha-025 and 0.1.0-beta001

### ISSUE THREAD

**Issue by ryukinix** [dustinmoris/Giraffe#80]
I don't know if this was intended, but based on the template of few days ago when I try compile my project with the new version, I got:

```
"/home/lerax/Desktop/dchart/src/Backend/Backend.fsproj" (default target) (1) ->
(CoreCompile target) -> 
  /home/lerax/Desktop/dchart/src/Backend/Server.fs(40,13): error FS0001: Type mismatch. Expecting a    'HttpContext -> 'a'    but given a    'HttpFunc -> 'b -> HttpFuncResult'    The type 'HttpContext' does not match the type 'HttpFunc' [/home/lerax/Desktop/dchart/src/Backend/Backend.fsproj]
  /home/lerax/Desktop/dchart/src/Backend/Server.fs(40,13): error FS0001: Type mismatch. Expecting a    'HttpContext -> 'a'    but given a    'HttpFunc -> 'b -> HttpFuncResult'    The type 'HttpContext' does not match the type 'HttpFunc' [/home/lerax/Desktop/dchart/src/Backend/Backend.fsproj]
  /home/lerax/Desktop/dchart/src/Backend/Server.fs(47,32): error FS0001: The type 'HttpFunc' is not compatible with the type 'HttpContext' [/home/lerax/Desktop/dchart/src/Backend/Backend.fsproj]

```

Running through 0.1.0-alpha-025 I got compiling fine, I just want know what is design changes on the new beta.

Where the source is basically the template default:
![image](https://user-images.githubusercontent.com/7642878/29249323-8ab127da-8003-11e7-8b52-29e5ee3a5a86.png)

**Comment by gerardtoconnor** [comment]
The error handler needs to be updated to use new HttpHandler format such that it additionally accepts a 'HttpFunc' functions as well as 'HttpContext' like 'fun next ctx ->. ..'

In the last line where handlers are composed, instead of 'ctx |> (handler)' you need to apply both parameters to functions like '(handler) next ctx'

**Comment by ryukinix** [comment]
Yes, I understand.  What you said fixed the problem. I can know why this change was made? Is related to the new `Task` support #53?

If anyone struggle with it too, the new errorHandler which works is it:

```fsharp
// ---------------------------------
// Error handler
// ---------------------------------

let errorHandler (ex : Exception) (logger : ILogger) (next: HttpFunc) (ctx : HttpContext) =
    logger.LogError(EventId(0), ex, "An unhandled exception has occurred while executing the request.")
    (clearResponse >=> setStatusCode 500 >=> text ex.Message) next ctx
```

**Comment by gerardtoconnor** [comment]
Both this continuation update and task were done for performance reasons, you can read blog post I did to explain performance benefits here if your interested.

https://medium.com/@gerardtoconnor/carry-on-continuation-over-binding-pipelines-for-functional-web-58bd7e6ea009

It's a slightly more complex way of doing the handlers but there is a focus on performance the consensus was it was worth breaking now for the long run.

If you have anymore issues let me know, happy to help.

**Comment by dustinmoris** [comment]
Apologies for this issue. Even though I have updated the latest giraffe-template, the previous versions break now when you pull the beta package from an alpha template. I should have not referenced giraffe with a wildcard in the .fsproj. I will set it to a specific version going forward with the new template releases, but meanwhile if someone runs into this issue you can either pin the latest giraffe alpha package, or preferably update the error handler to match the new beta. You can simplify the error handler even further:

```fsharp
let errorHandler (ex : Exception) (logger : ILogger) =
    logger.LogError(EventId(), ex, "An unhandled exception has occurred while executing the request.")
    clearResponse >=> setStatusCode 500 >=> text ex.Message
```
