### ISSUE TITLE
Serialization/Deserialization performance

### ISSUE THREAD

**Issue by Lanayx** [dustinmoris/Giraffe#82]
According to [this](http://www.newtonsoft.com/json/help/html/Performance.htm) and other links serialization and deserialization should be done by using streams, not strings. And currently all helper extensions use strings. Was it intentional or this should be fixed?

**Comment by Banashek** [comment]
I believe this would largely depend on the size of the json you're sending.

I have a feeling that for most use cases (under the 85kb size specified in the linked documentation), that the cost of setting up the `Stream`, `StreamReader`, and `JsonReader` could potentially take longer for smaller sized json values.

If your application is a streaming dashboard pushing huge lists of types many times per second, then you'll probably want to make that more efficient.

The json serializer helper found in the Common.fs file is found in one place: https://github.com/dustinmoris/Giraffe/blob/c65b2bfbb350318344de397a9addd1c6898cf720/src/Giraffe/HttpHandlers.fs#L299 .

If the use case fell under extreme perfomance, you could implement the 3 line `json` method with a custom serializer.

**Comment by Lanayx** [comment]
Ok, thank you for response. Currently I'm testing Giraffe at highload and trying to find the room for improvement. Will respond here if streams help.

**Comment by Lanayx** [comment]
This idea didn't work for me, since it is impossible to set content-length in case of writing directly to stream. Closing the issue.
