### ISSUE TITLE
VS2017 (full .NET framework) support

### ISSUE THREAD

**Issue by AlbertoDePena** [dustinmoris/Giraffe#87]
Fantastic work! Working through a demo with vscode (netcoreapp1.1) and @swlaschin's ROP idea...

Wanted to ask if there is a sample or template to get started with VS 2017 (Solution and fsproj). I was hoping to run the app with full .net framework (net46) that way when I deploy, it'll generate a .exe and update the web.config... Any light on this would be greatly appreciated =)

**Comment by dustinmoris** [comment]
Hi, You can use Giraffe with the full framework, for this you just have to adjust the `.fsproj` file like this:

```xml
  <PropertyGroup>
    <TargetFramework>net46</TargetFramework>
    <DebugType>portable</DebugType>
    <AssemblyName>YourAppName</AssemblyName>
    <OutputType>Exe</OutputType>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
    <RuntimeIdentifier>win7-x64</RuntimeIdentifier>
  </PropertyGroup>
```

But as far as I know the VS 2017 experience is still not great. Currently the best way to work with F# and the new project template is to use VS Code and the Ionide project.

**Comment by AlbertoDePena** [comment]
You are correct! =/ My issue is debugging in vscode... I have no problem debugging when the target framework is netcoreapp1.1. I cannot get the debugging to work for net46 (or a full framework for that matter). When I set target framework with both netcoreapp1.1 and net46, I can work with that but I get some errors. I saw in Giraffe's home page that a powershell script is provided to aid in that (Build.ps1). Where can I locate that script?

Oh and thanks so much for your response =)

**Comment by AlbertoDePena** [comment]
@dustinmoris nvm, I was able to deploy to FileSystem and WebPackage but it took some steps:

1. Create a sln for the .fsproj
2. Add the .fsproj to the sln
3. Open sln with VS2017
4. Create publish profile (FileSystem and/or WebPackage)
5. Using VS2017, publish the application

This gave me what I needed including the transformation of the web.config (updated system.WebServer %Variables%)

Pretty cool =)

**Comment by dustinmoris** [comment]
Nice, glad you got it working!
