### ISSUE TITLE
Update to template .fsproj references unpublished Giraffe.Razor version

### ISSUE THREAD

**Issue by mtnrbq** [dustinmoris/Giraffe#89]
Hi,
the .fsproj for the latest template includes:
`<PackageReference Include="Giraffe.Razor" Version="0.1.0-beta-002" />`

however, the latest version on Nuget for Giraffe.Razor is ...beta-001

I'm guessing the template update was meant to be:
`<PackageReference Include="Giraffe" Version="0.1.0-beta-002" />`
but wanted to check.

**Comment by dustinmoris** [comment]
You're right, thanks for reporting!
