### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by ShalokShalom** [dustinmoris/Giraffe#94]
Is this still considered? https://github.com/dustinmoris/Giraffe#sample-applications
I guess there are already some projects successfully build?

**Comment by dustinmoris** [comment]
Hi, I will still be linking to more sample applications in the future if someone builds something new with Giraffe which hasn't been shown in one of the other examples yet.

Have you got something interesting which you would like me to link to? :)

**Comment by ShalokShalom** [comment]
Nope. I am simply asking myself, if that is already all, which is available. :)
