### ISSUE TITLE
New to Giraffe and F#

### ISSUE THREAD

**Issue by AlbertoDePena** [dustinmoris/Giraffe#95]
I would love some constructive criticism on this project I am working on. I needed something concrete to get my hands on F#. Im looking for things I could do better that are super obvious...

Link to project:

https://github.com/AlbertoDePena/VisitorTrack/tree/master/VisitorTrack.Web

Note: I am using Scott Wlaschin's ROP ideas =)

**Comment by dustinmoris** [comment]
Hi Alberto,

Your code looks well structured in my opinion and quite good. I had only a brief look, but the only thing I would certainly suggest is to not keep any secret data like the default password in your code. Move it to some environment variable, but in the case of a default password I'd suggest to use a cryptographic randomizer to generate a new random string for each user.

Perhaps link your repo in the [functional programming Slack channel](https://functionalprogramming.slack.com/) to get more people have a look at your code!

**Comment by AlbertoDePena** [comment]
That is a very good suggestion. Thank you so much =)

**Comment by dustinmoris** [comment]
Closing this issue, but let me know if there's anything I can help with otherwise!
