### ISSUE TITLE
Enable windows auth

### ISSUE THREAD

**Issue by AlbertoDePena** [dustinmoris/Giraffe#96]
I am running a giraffe app with vscode. I have windows enabled and anonymous disabled (launchsettings.json). I cannot get the identity to populate the user. Any suggestions?

**Comment by dustinmoris** [comment]
Can you link a repo where this can be reproduced or a small app?

**Comment by AlbertoDePena** [comment]
Sure thing. https://github.com/AlbertoDePena/VisitorTrack/tree/master/VisitorTrack.Web

To run the app:
dotnet run.

Thanks =)

**Comment by dustinmoris** [comment]
Sorry for being slow with this... I had a quick look by downloading your app but didn't know how to reproduce your issue. Could you provide me exact steps? I will pick this one up tomorrow evening latest and let you know where I got with it! Thank you for your patience!

**Comment by dustinmoris** [comment]
Hi @AlbertoDePena, f you could provide me more detailed reproduction steps please, because I wasn't sure how to test for your issue after pulling the repo.

**Comment by AlbertoDePena** [comment]
@dustinmoris nvm, I was able to fix my issue. Thanks for looking into it. I ll go ahead and close this issue, you're the man!
