### ISSUE TITLE
How to debug in VS Code/Ionide

### ISSUE THREAD

**Issue by jimfoye** [dustinmoris/Giraffe#99]
I have the .NET 2.0 core debugger installed, courtesy of the C# extension. I assume I will use the configuration ".NET Core Launch (web)", is that correct?

When I try that I get error messages about configuring launch.json and task.json. Is there a good walk-through on this somewhere?

**Comment by AlbertoDePena** [comment]
When it prompts you for the launch.json / task.json you must create / configure them. Use this link for steps on how to accomplish that...

https://code.visualstudio.com/docs/editor/debugging

Once you create the json files, just make sure the program property points to the web app dll.

**Comment by jimfoye** [comment]
Ok, thanks, and found some help here, too.

[https://blogs.msdn.microsoft.com/dotnet/2017/09/26/build-a-web-service-with-f-and-net-core-2-0/](url)

All good now.
